In [1]:
import numpy as np

from qiskit_dynamics.pulse.pulse_utils import tensor_state_label_generator, get_dressed_state_data

In [2]:
tensor_state_label_generator(subsystem_dims=[3, 3, 2])

['000',
 '001',
 '002',
 '010',
 '011',
 '012',
 '020',
 '021',
 '022',
 '100',
 '101',
 '102',
 '110',
 '111',
 '112',
 '120',
 '121',
 '122']

In [3]:
get_dressed_state_data(np.array([[-1., 0.], [0., 1.]]), subsystem_dims=[2])

(array([-1.,  1.]),
 array([[1., 0.],
        [0., 1.]]))

In [4]:
test[-3]

0

In [5]:
[0, 0, 0] + [1]

[0, 0, 0, 1]

In [6]:
[] + [1]

[1]

In [7]:
[1][1:]

[]

In [8]:
list(range(1, 2))

[1]

In [5]:
from qiskit.quantum_info import Statevector, DensityMatrix

In [11]:
test = Statevector(np.sqrt([0, 0.5, 0.25, 0.25, 0., 0.]), dims=(3,2))

In [12]:
test.probabilities()

array([0.  , 0.5 , 0.25, 0.25, 0.  , 0.  ])

In [21]:
test.sample_counts(shots=5, qargs=[0])

{'0': 2, '1': 3}

In [10]:
help(test.sample_counts)

Help on method sample_counts in module qiskit.quantum_info.states.quantum_state:

sample_counts(shots, qargs=None) method of qiskit.quantum_info.states.statevector.Statevector instance
    Sample a dict of qubit measurement outcomes in the computational basis.
    
    Args:
        shots (int): number of samples to generate.
        qargs (None or list): subsystems to sample measurements for,
                            if None sample measurement of all
                            subsystems (Default: None).
    
    Returns:
        Counts: sampled counts dictionary.
    
    Additional Information:
    
        This function *samples* measurement outcomes using the measure
        :meth:`probabilities` for the current state and `qargs`. It does
        not actually implement the measurement so the current state is
        not modified.
    
        The seed for random number generator used for sampling can be
        set to a fixed value by using the stats :meth:`seed` method.



In [38]:
test = [1, 2, 3]

In [39]:
test.append(4)

In [40]:
test

[1, 2, 3, 4]