In [1]:
import numpy as np

from qiskit_dynamics.pulse.pulse_utils import tensor_state_label_generator, get_dressed_state_data

In [2]:
tensor_state_label_generator(subsystem_dims=[3, 3, 2])

['000',
 '001',
 '002',
 '010',
 '011',
 '012',
 '020',
 '021',
 '022',
 '100',
 '101',
 '102',
 '110',
 '111',
 '112',
 '120',
 '121',
 '122']

In [3]:
get_dressed_state_data(np.array([[-1., 0.], [0., 1.]]), subsystem_dims=[2])

(array([-1.,  1.]),
 array([[1., 0.],
        [0., 1.]]))

In [4]:
test[-3]

0

In [5]:
[0, 0, 0] + [1]

[0, 0, 0, 1]

In [6]:
[] + [1]

[1]

In [7]:
[1][1:]

[]

In [8]:
list(range(1, 2))

[1]

In [12]:
from qiskit.quantum_info import Statevector

In [35]:
test = Statevector(np.sqrt([0, 0.5, 0.25, 0.25, 0., 0.]), dims=(3,2))

In [36]:
test.probabilities()

array([0.  , 0.5 , 0.25, 0.25, 0.  , 0.  ])

In [37]:
test.probabilities_dict()

{'01': 0.5000000000000001, '02': 0.25, '10': 0.25}

In [38]:
test = [1, 2, 3]

In [39]:
test.append(4)

In [40]:
test

[1, 2, 3, 4]